version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - TZ=America/Toronto
    restart: always

volumes:
  mongodb_data:
